using CustomTools.StringApproxAlgorithms.Eltin_Buchard_Keller_Algorithm;
using CustomTools.StringApproxAlgorithms.SymSpellAlgorithm;

//EltinBuchardKellerAlgorithEntrypoint.DemonstrateTheAlgorith();
StringApproximationBySymSpell.InvokeSymSpellExamples();