name: CI
on:                               #Here "on push" were deleted, because it should be in CD (deploy file), here only for pull requests.
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter DisplayName=UniversityEntrypoints.WebApi.DemoTest.ContinuousIntegrationTest
