name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./ASP.NETCoreWebAPI/ASP.NETCoreWebAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api #-o is output folder. ${{ env.DOTNET_ROOT }} is to use here an environmental variable that is defined in Setup .NET Core SDK and aim at root folder (despite the operating system). Moreover, use just one project not all
      - name: upload artifact
        uses: actions/upload-artifact@v3.0.0
        with: 
          name: api-artifact    #custom name for artifact. Artifacts are data that can be share between different steps, therefore we need to upload id (use marketplace template)
          path: ${{ env.DOTNET_ROOT }}/api   #our artifact path to the published api
  
#  deploy-dev:     #new job
#    runs-on: ubuntu-latest
#    needs: build   #we say that this job need previous job to be done
#    environment:    #environmental variables for managing pipielines
#      name: 'Dev'   #strings are in single quotes. Name of the environment
#      url: ${{ steps.deploy-to-somewhere.outputs.webapp-url }}  #In order to get the url from the further defined step, we do like this (need to refer id)
#    steps: 
#      - name: Download a Build Artifact   
#        uses: actions/download-artifact@v3.0.0
#        with: 
#          name: api-artifact       #same name as in build step
#      - name: Somewhere WebApp deploy   #name of the way for we deploy the app. It can be Azure WebApp or other
#        id: deploy-to-somewhere       #In order to refer this step we need to add id to it
#        uses: Azure/webapps-deploy@v2   #This is about to deploy on Azure Service
#        with:
#          app-name: 'CSharpUniversity-dev'
#          publish-profile: ${{ secrets.CUSTOM_PUBLISH_PROFILE_DEV }}
#   
#  deploy-prod:     
#    runs-on: ubuntu-latest
#    needs: deploy-dev   #we say that this job need previous job to be done
#    environment:    
#      name: 'Prod'   
#      url: ${{ steps.deploy-to-somewhere.outputs.webapp-url }}  #In order to get the url from the further defined step, we do like this (need to refer id)
#    steps: 
#      - name: Download a Build Artifact   
#        uses: actions/download-artifact@v3.0.0
#        with: 
#          name: api-artifact      
#      - name: Somewhere WebApp deploy   
#        id: deploy-to-somewhere       
#        uses: Azure/webapps-deploy@v2   #This is about to deploy on Azure Service
#        with:
#          app-name: 'CSharpUniversity-prod'
#          publish-profile: ${{ secrets.CUSTOM_PUBLISH_PROFILE_PROD }}         
          
          
          
