name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./ASP.NETCoreWebAPI/ASP.NETCoreWebAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api #-o is output folder. ${{ env.DOTNET_ROOT }} is to use here an environmental variable that is defined in Setup .NET Core SDK and aim at root folder (despite the operating system). Moreover, use just one project not all
      - name: upload artifact
        uses: actions/upload-artifact@v3.0.0
        with: 
          name: api-artifact    #custom name for artifact. Artifacts are data that can be share between different steps, therefore we need to upload id (use marketplace template)
          path: ${{ env.DOTNET_ROOT }}/api   #our artifact path to the published api
  
  deploy-dev:     #new job
    runs-on: ubuntu-latest
    needs: build   #we say that this job need previous job to be done
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with: 
          name: api-artifact       #same name as in build step
          
          
          
